- package-lock.json
- package.json
- src/components/course-list.js
- src/components/header.js
- src/components/landing-page.js
- src/get-page-context.js
- src/with-root.js
Used `react-google-login` for auth, login works using client id from angular source.
User object with token received successfully.
Looking into ways to manage a user session and store the received token now.
Tips welcome.
> [WIP] Authentication

- package-lock.json
- package.json
- pages/course.js
- src/components/course-detail.js
- src/components/course-list.js
- src/components/header.js
- src/components/landing-page.js
- src/services/api.js
- src/services/config.js
A basic implementation of auth using google auth and Saral APIs to get started. Have marked a lot of TODOs in the code, which needs to be addresses. 
Referencing - https://github.com/navgurukul/kamaladevi/issues/1
> Auth Implementation

- src/components/course-list.js
Re Issue #5 and #6,
@credifiable, could you please help figure out the following,
* What would you suggest would be a good way to arrange the cards in columns here? Is there a bootstrap plugin for react you could recommend?
* The console is throwing the above shown error when a `button` element is placed under a `card`. Why might this be? (course-list.js: line 96 and 128, code below for reference)
```
{availableCourses.map(value => (
<div key={value.id} >
<Card variant="raised" className={classes.card}>
<CardContent>
<Typography variant="headline" component="h2">
{value.name}
</Typography>
<Typography color="textSecondary">
{value.shortDescription}
</Typography>
</CardContent>
<CardActions aligh="end">
<Button
size="small"
variant="raised"
color="primary"
className={classes.button} …
```
> [WIP] UI Changes

- src/components/header.js
- src/components/landing-page.js
Fixed minor issues, #9, #10, and #18
> Minor fixes

- package-lock.json
- package.json
- src/components/course-detail-sidenav.js
- src/components/course-detail.js
- src/components/course-list.js
- src/components/header.js
- src/components/landing-page.js
- src/services/api.js
- src/services/courses.js
- src/services/session.js
@credifiable, I'm presently using the `List` element from Material UI. Suggestions for collapsible list implementation for hierarchical presentation?
> [WIP] Course content switcher

- pages/course.js
- src/components/course-detail-sidenav.js
- src/components/course-detail.js
- src/components/course-list.js
- src/components/landing-page.js
- src/services/courses.js
Will contain new enhancements for next branch.
> Enhancements 2

- .gitignore
- package-lock.json
- package.json
- src/components/course-detail.js
- src/components/landing-page.js
Added a min-width to fix the login page in mobile apps.
> Login page

- src/components/course-detail-sidenav.js
Added the code for Unenroll button and Notification that should be shown after a person has enrolled
@abhishekgupta92
> added unenroll button and notifier

- src/components/course-list.js
Removed preview button and added Link component in place of that. 
@abhishekgupta92
> Removed preview button #27

- src/components/course-detail.js
Removed the next button from the last page and previous button from the first page
> added next and previous button edge cases #30

- pages/course.js
Links which are inside the courses are being open in a new tab
> links inside open in new tab #37

- src/components/course-list.js
fixed heading displaying issue when there is no course under that section in the home page
> fixed heading not to display when they are empty #36

- src/components/course-detail.js
Adjusted the size of image to fit in.
> image width adjusted to 100% #31

- pages/course.js
- src/components/course-detail.js
Fixed the new-tab issue and limited it only the course detail part.
> fixed the course detail to open in new tab #45

- src/components/course-detail.js
The remaining commit related to next and previous button commit where the next button should always be on right
> Next previous button

- package-lock.json
- package.json
- pages/course.js
- src/components/comments.js
- src/components/course-detail.js
Disqus commenting system used disqus-react
> Added comment

- package-lock.json
- src/components/course-detail.js
> image displaying to center #38

- package-lock.json
- package.json
- pages/course.js
- src/components/course-detail.js
- src/services/courses.js
Used slug as the meaning title for this.
> added title for different pages #50

- src/services/courses.js
meaning-titles issue resolved!
> meaning-titles done

- src/components/course-detail.js
- src/services/config.js
added alert messages for different submissionType
> Alert message

- package-lock.json
- package.json
- pages/home.js
- src/components/course-detail-sidenav.js
- src/components/course-detail.js
- src/components/course-list.js
- src/components/courses-list/course-delete-alert.js
- src/components/courses-list/course-list-card.js
- src/components/courses-list/course-list-category.js
- src/components/courses-list/course-list-dragdrop.js
- src/components/courses-list/index.js
- src/components/header.js
- src/components/landing-page.js
- src/get-page-context.js
- src/services/config.js
- src/services/courses.js
Added Drag and Drop feature for Admin run the script provided in SQL script in the backend and also do check the responsive I think the responsive is being compromised and what can be a better solution to achieve this?
I have tested it out in local please test it in local :p
> Drag drop courses

- package.json
- pages/course.js
- src/components/course-detail/index.js
- src/components/course-detail/utterances.js
fixed the utterances problem remove the react-utterances from dependency
> utterances fixed

- src/get-page-context.js
> Changed primary colors to orange

- pages/course.js
- pages/home.js
- src/components/course-detail/index.js
> live bugs fixed

- pages/githubAccess.js
- pages/index.js
- pages/login.js
- src/components/course-detail/course-detail-sidenav.js
- src/components/courses-list/course-list-category-card.js
- src/components/courses-list/course-list-dragdrop-card.js
- src/components/header.js
- src/components/landing-page.js
- src/services/api.js
- src/services/session.js
github study pack access given to student
> github access given to student

- package.json
- src/components/courses-list/course-list-category-card.js
- src/components/courses-list/course-list-dragdrop-card.js
@abhishekgupta92 Need your thoughts on the changes, and suggestions for navbar?
> [WIP] Larger cards on homepage
